version: '3.8'
services:
  app:
    build: ../../lab-1/java-springboot/2-complete-auto
    ports:
      - 4321:4321
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
  otel-collector:
    image: otel/opentelemetry-collector:0.80.0
    ports:
      - 4317:4317
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
