receivers:
  otlp:
    protocols:
      grpc:
        
processors:
  batch:
  probabilistic_sampler:
    sampling_percentage: 20

exporters:
  otlphttp:
    auth:
      authenticator: basicauth
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    
extensions:
  basicauth:
    client_auth:
      username: ${env:GRAFANA_CLOUD_INSTANCE_ID}
      password: ${env:GRAFANA_CLOUD_TOKEN}
        
service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,probabilistic_sampler]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
